# Generated by Django 5.0.6 on 2024-12-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('tickets_sold', models.PositiveIntegerField(default=0)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('event_image', models.URLField(blank=True, null=True)),
                ('gallery', models.JSONField(blank=True, null=True)),
                ('organizer_name', models.CharField(max_length=255)),
                ('organizer_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('rsvp_count', models.PositiveIntegerField(default=0)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('canceled', 'Canceled')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_datetime'],
            },
        ),
    ]
