# Generated by Django 5.0.6 on 2024-10-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_payment_delivery_address_payment_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='country_code',
            field=models.CharField(default=233, max_length=255),
            preserve_default=False,
        ),
    ]
