# Generated by Django 5.0.6 on 2024-10-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='delivery_price',
            field=models.IntegerField(default=0),
        ),
    ]
