# Generated by Django 5.0.6 on 2024-11-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_category_product_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
