# Generated by Django 5.0.6 on 2024-12-04 17:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_outing_tickettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='outing',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
