# Generated by Django 5.1.3 on 2024-12-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(blank=True, default=0, null=True),
        ),
    ]
