# Generated by Django 5.1.3 on 2024-12-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_cart_payment_alter_relatedimages_product_cartobject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='batch',
            field=models.TextField(blank=True, null=True),
        ),
    ]
