# Generated by Django 5.1.3 on 2024-12-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_newsletter_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='batch_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
