# Generated by Django 5.1.3 on 2024-12-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_newsletter_batch_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.TextField(blank=True, null=True)),
                ('batch_size', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='batch_size',
        ),
    ]
