# Generated by Django 5.1.3 on 2024-12-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_newsletterbatch_remove_newsletter_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Tees', 'Tees'), ('Slides', 'Slides'), ('Joggers', 'Joggers')], max_length=7, null=True),
        ),
    ]
