# Generated by Django 5.1.3 on 2024-12-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
