# Generated by Django 5.1.3 on 2025-01-02 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_newsletter_first_name_newsletter_last_name'),
        ('userAdmin', '0004_notification_viewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': [models.Case(models.When(category='Tees', then=0), models.When(category='Slides', then=1), models.When(category='Joggers', then=2), default=3, output_field=models.IntegerField()), 'name']},
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAdmin.notification')),
            ],
        ),
    ]
