# Generated by Django 5.1.3 on 2025-01-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_product_options_contact'),
        ('userAdmin', '0004_notification_viewed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactModel',
        ),
    ]
