# Generated by Django 5.1.3 on 2025-01-02 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_contact'),
        ('userAdmin', '0004_notification_viewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': [models.Case(models.When(category='Tees', then=0), models.When(category='Slides', then=1), models.When(category='Joggers', then=2), default=3, output_field=models.IntegerField()), 'name']},
        ),
        migrations.AddField(
            model_name='contact',
            name='notification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAdmin.notification'),
        ),
    ]
