# Generated by Django 5.1.3 on 2025-01-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_contact_contactmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
