# Generated by Django 5.1.3 on 2025-01-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': [models.Case(models.When(category='Tees', then=0), models.When(category='Slides', then=1), models.When(category='Joggers', then=2), models.When(category='Caps', then=3), default=4, output_field=models.IntegerField()), 'name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Tees', 'Tees'), ('Slides', 'Slides'), ('Joggers', 'Joggers'), ('Caps', 'Caps')], max_length=7, null=True),
        ),
    ]
