# Generated by Django 5.1.3 on 2025-01-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': [models.Case(models.When(category__name='Tees', then=0), models.When(category__name='Slides', then=1), models.When(category__name='Joggers', then=2), models.When(category__name='Caps', then=3), default=4, output_field=models.IntegerField()), 'name']},
        ),
    ]
