# Generated by Django 5.1.3 on 2025-01-03 09:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
