# Generated by Django 5.1.3 on 2025-01-03 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_size_sizeset_product_size_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeset',
            name='sizes',
        ),
        migrations.AddField(
            model_name='size',
            name='sizeSet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sizeset'),
        ),
    ]
