# Generated by Django 5.1.3 on 2025-01-04 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_sizeset_sizes_size_sizeset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='sizeSet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizes', to='home.sizeset'),
        ),
    ]
