# Generated by Django 5.1.3 on 2025-01-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_size_sizeset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_ordering']},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
