# Generated by Django 5.1.3 on 2025-01-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_product_options_alter_product_product_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
