# Generated by Django 5.1.3 on 2025-01-07 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediumLargeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.PositiveIntegerField(default=0)),
                ('large', models.PositiveIntegerField(default=0)),
                ('xl', models.PositiveIntegerField(default=0)),
                ('xl2', models.PositiveIntegerField(default=0)),
                ('xl3', models.PositiveIntegerField(default=0)),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mediumLargeStock', to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Size39to46',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size39', models.PositiveIntegerField(default=0)),
                ('size40', models.PositiveIntegerField(default=0)),
                ('size41', models.PositiveIntegerField(default=0)),
                ('size42', models.PositiveIntegerField(default=0)),
                ('size43', models.PositiveIntegerField(default=0)),
                ('size44', models.PositiveIntegerField(default=0)),
                ('size45', models.PositiveIntegerField(default=0)),
                ('size46', models.PositiveIntegerField(default=0)),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='size39to46', to='home.product')),
            ],
        ),
    ]
