# Generated by Django 5.1.3 on 2025-01-07 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_mediumlargestock_size39to46'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediumlargestock',
            old_name='medium',
            new_name='Medium',
        ),
        migrations.AddField(
            model_name='mediumlargestock',
            name='size_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sizeset'),
        ),
        migrations.AddField(
            model_name='size39to46',
            name='size_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sizeset'),
        ),
    ]
