# Generated by Django 5.1.3 on 2025-01-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_rename_medium_mediumlargestock_medium_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediumlargestock',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='size39to46',
            old_name='Product',
            new_name='product',
        ),
    ]
