# Generated by Django 5.1.3 on 2025-01-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_rename_product_mediumlargestock_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediumlargestock',
            old_name='Medium',
            new_name='medium',
        ),
    ]
