# Generated by Django 5.1.3 on 2025-01-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_rename_medium_mediumlargestock_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
