# Generated by Django 5.1.3 on 2025-01-10 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_size_value_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumlargestock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediumLargeStock', to='home.product'),
        ),
        migrations.AlterField(
            model_name='size39to46',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size39to46', to='home.product'),
        ),
    ]
