# Generated by Django 5.1.3 on 2025-01-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_mediumlargestock_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['size_ordering']},
        ),
        migrations.AddField(
            model_name='size',
            name='size_ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
