# Generated by Django 5.1.3 on 2025-01-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_size_options_size_size_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartobject',
            name='sizeData',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
