# Generated by Django 5.1.3 on 2025-01-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_cartobject_sizedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pickupdata',
            field=models.BooleanField(default=False),
        ),
    ]
