# Generated by Django 5.1.3 on 2025-01-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_payment_pickupdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='accralocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
