# Generated by Django 5.1.3 on 2025-02-20 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order']},
        ),
    ]
