# Generated by Django 5.1.3 on 2025-06-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='size39to46',
            name='size38',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
