# Generated by Django 5.0.6 on 2024-10-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_unique_id'),
        ('shop', '0005_relatedimages'),
    ]

    operations = [
    ]
