# Generated by Django 5.0.6 on 2024-10-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_merge_0004_alter_product_unique_id_0005_relatedimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorName', models.CharField(max_length=255)),
                ('colorCode', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='relatedimages',
            name='color',
            field=models.ManyToManyField(default=None, to='shop.color'),
        ),
    ]
