# Generated by Django 5.0.6 on 2024-10-23 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_color_relatedimages_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_color',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.color'),
        ),
        migrations.AlterField(
            model_name='relatedimages',
            name='color',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='shop.color'),
        ),
    ]
