# Generated by Django 5.0.6 on 2024-10-27 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_cart_cartobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartobject',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_objects', to='shop.cart'),
        ),
    ]
