# Generated by Django 5.1.3 on 2024-12-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.CharField(max_length=255)),
                ('revenue', models.CharField(max_length=255)),
                ('subscribers', models.CharField(max_length=255)),
            ],
        ),
    ]
