# Generated by Django 5.1.3 on 2024-12-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('january', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('february', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('march', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('april', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('may', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('june', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('july', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('august', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('september', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('october', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('november', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('december', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.DeleteModel(
            name='StoreData',
        ),
    ]
