# Generated by Django 5.1.3 on 2024-12-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0002_revenue_delete_storedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(blank=True, choices=[('Product Sold', 'Productsold'), ('NewsLetter Addition', 'Newsletteraddition'), ('Contact Form', 'Contactform')], max_length=100, null=True)),
            ],
        ),
    ]
