# Generated by Django 5.1.3 on 2024-12-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
