# Generated by Django 5.1.3 on 2025-01-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0005_deliverypricebyregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPriceByAccra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_method', models.CharField(max_length=100, unique=True)),
                ('adenta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('achimota', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('circle', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lapaz', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('west_hills', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dome', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ashaley_botwe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('madina', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('east_legon', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('west_land', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('north_legon', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('legon_campus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dansoman', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mataheko', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cantonments', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('labone', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('osu', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('spintex', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tema', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('kwabenya', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lakeside', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ashongman', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('adjiringanor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('east_legon_hills', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('airport_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('teshie', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
