# Generated by Django 5.1.3 on 2025-01-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0006_deliverypricebyaccra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypricebyaccra',
            name='delivery_method',
        ),
    ]
