# Generated by Django 5.1.3 on 2025-01-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAdmin', '0007_remove_deliverypricebyaccra_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypricebyaccra',
            name='not_listed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
